import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import Menubar from "./Components/Menubar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-blue-900 z-50 text-center fixed w-full top-0 left-0 py-6">
          <div className="max-w-7xl w-full mx-auto px-2 flex justify-between">
            <Menubar></Menubar>
            <Link href={'/'}>
              <h2 className="tracking-widest text-white">EchoGPT</h2>
            </Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
