import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-gray-200 z-50 text-center fixed w-full top-0 left-0 py-6">
          <div className="max-w-7xl w-full mx-auto flex justify-between">
            <Image src={'/icons8-menu-144.png'} className="lg:hidden" alt="menu icon" height={30} width={30}></Image>
            <h2 className="tracking-widest">EchoGPT</h2>
            <p className="text-sm font-bold">user</p>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
